/**
 * Smash Party fighter roster — pure data (no three.js / DOM), imported by the phone too.
 * Ids, names and colours come from the Kart Party roster (src/kart/roster.ts → getCharacter(id)).
 * Move FRAME DATA lives in src/games/smash/sim/movesets.ts; this file holds stats + UI text.
 *
 * Units: world units (≈ classic smash units / 10), frames at 60 Hz.
 */
import type { FighterDef } from './types';

export const FIGHTERS: FighterDef[] = [
  // ---------------------------------------------------------------- zippy
  {
    id: 'zippy',
    archetype: 'speedster',
    archetypeLabel: 'SPEEDY COMBO',
    bars: { power: 2, speed: 5, weight: 1, jump: 4, range: 2 },
    weight: 72,
    walkSpeed: 0.14,
    runSpeed: 0.235,
    airSpeed: 0.135,
    airAccel: 0.011,
    gravity: 0.0105,
    fallSpeed: 0.18,
    fastFallSpeed: 0.28,
    jumpVel: 0.27,
    shortHopVel: 0.185,
    doubleJumpVel: 0.26,
    height: 1.6,
    width: 0.7,
    specials: {
      neutral: { name: 'Pinball Spin', desc: 'Curl up and ricochet forward in a multi-hit spin.' },
      side: { name: 'Slipstream Dash', desc: 'A blinding dash that slices through foes. Works in the air.' },
      up: { name: 'Corkscrew Climb', desc: 'Spiral straight up, hitting everything on the way. Steer with the stick.' },
      down: { name: 'Tailwind Kick', desc: 'Drop into a fast diving kick that bounces you back up on hit.' },
    },
    finalSmash: { name: 'Hyper Lap', desc: 'Zip back and forth across the stage in a blur of hits.' },
    tip: 'Never stop moving: jab, dash in, juggle with up air!',
    polished: true,
  },
  // ---------------------------------------------------------------- pixel
  {
    id: 'pixel',
    archetype: 'zoner',
    archetypeLabel: 'BUBBLEGUM ZONER',
    bars: { power: 2, speed: 3, weight: 1, jump: 4, range: 4 },
    weight: 78,
    walkSpeed: 0.11,
    runSpeed: 0.17,
    airSpeed: 0.115,
    airAccel: 0.01,
    gravity: 0.0078,
    fallSpeed: 0.135,
    fastFallSpeed: 0.22,
    jumpVel: 0.245,
    shortHopVel: 0.17,
    doubleJumpVel: 0.25,
    height: 1.55,
    width: 0.72,
    specials: {
      neutral: { name: 'Gum Bomb', desc: 'Lob a sticky bubble-gum bomb that pops after a moment.' },
      side: { name: 'Sugar Rush', desc: 'Skate forward on a candy streak, bumping foes away.' },
      up: { name: 'Bubble Lift', desc: 'Blow a huge bubble and float up with it. Pops on foes.' },
      down: { name: 'Pop Rocks', desc: 'Scatter fizzy candy that crackles on the ground.' },
    },
    finalSmash: { name: 'Sugar Storm', desc: 'A storm of giant gum bombs rains down on the whole stage.' },
    tip: 'Lob gum bombs from afar, then float away with Bubble Lift.',
    polished: false,
  },
  // ---------------------------------------------------------------- fennec
  {
    id: 'fennec',
    archetype: 'trickster',
    archetypeLabel: 'TRICKSTER',
    bars: { power: 3, speed: 4, weight: 2, jump: 4, range: 3 },
    weight: 82,
    walkSpeed: 0.125,
    runSpeed: 0.21,
    airSpeed: 0.125,
    airAccel: 0.01,
    gravity: 0.0095,
    fallSpeed: 0.165,
    fastFallSpeed: 0.26,
    jumpVel: 0.26,
    shortHopVel: 0.18,
    doubleJumpVel: 0.255,
    height: 1.6,
    width: 0.72,
    specials: {
      neutral: { name: 'Mirage Decoy', desc: 'Leave a shimmering copy of yourself that bursts when touched.' },
      side: { name: 'Fox Fire', desc: 'Toss a curving wisp of fire that hunts the nearest foe.' },
      up: { name: 'Blink Step', desc: 'Vanish and reappear in the stick direction. Very far, very sneaky.' },
      down: { name: 'Mirror Tail', desc: 'Spin your tail to reflect projectiles and bat foes away.' },
    },
    finalSmash: { name: 'Mirage Ambush', desc: 'Blink around the stage, striking every foe from every side.' },
    tip: 'Bait with decoys, reflect zoners, and Blink Step home from anywhere.',
    polished: true,
  },
  // ---------------------------------------------------------------- max
  {
    id: 'max',
    archetype: 'allrounder',
    archetypeLabel: 'ALL-ROUNDER',
    bars: { power: 3, speed: 3, weight: 3, jump: 3, range: 3 },
    weight: 98,
    walkSpeed: 0.115,
    runSpeed: 0.18,
    airSpeed: 0.12,
    airAccel: 0.009,
    gravity: 0.009,
    fallSpeed: 0.155,
    fastFallSpeed: 0.245,
    jumpVel: 0.25,
    shortHopVel: 0.172,
    doubleJumpVel: 0.245,
    height: 1.8,
    width: 0.8,
    specials: {
      neutral: { name: 'Vortex Ball', desc: 'Fire a bouncing ball of spinning wind.' },
      side: { name: 'Gust Cape', desc: 'Swirl a cape of wind that turns foes around and reflects shots.' },
      up: { name: 'Vortex Uppercut', desc: 'A rising multi-hit uppercut. Great to recover and to finish.' },
      down: { name: 'Cyclone Spin', desc: 'Spin in place like a tornado, pulling foes in, then fling them.' },
    },
    finalSmash: { name: 'Vortex Rush', desc: 'Charge forward inside a giant twister that sweeps foes away.' },
    tip: 'Good at everything: jab, tilt, then forward smash at high %!',
    polished: true,
  },
  // ---------------------------------------------------------------- juno
  {
    id: 'juno',
    archetype: 'zoner',
    archetypeLabel: 'PROJECTILE ZONER',
    bars: { power: 3, speed: 2, weight: 3, jump: 3, range: 5 },
    weight: 92,
    walkSpeed: 0.1,
    runSpeed: 0.165,
    airSpeed: 0.11,
    airAccel: 0.0085,
    gravity: 0.0082,
    fallSpeed: 0.145,
    fastFallSpeed: 0.23,
    jumpVel: 0.24,
    shortHopVel: 0.165,
    doubleJumpVel: 0.24,
    height: 1.8,
    width: 0.78,
    specials: {
      neutral: { name: 'Storm Bolt', desc: 'Hold to charge a lightning bolt — fully charged it is a KO shot.' },
      side: { name: 'Seeker Spark', desc: 'A slow spark that homes in on the nearest foe.' },
      up: { name: 'Thunder Leap', desc: 'Ride a lightning strike high into the air, zapping foes.' },
      down: { name: 'Static Field', desc: 'Burst of static all around you. Pushes foes off you.' },
    },
    finalSmash: { name: 'Storm Cannon', desc: 'Unleash a colossal lightning beam across the stage.' },
    tip: 'Keep your distance: charge Storm Bolt while they approach.',
    polished: true,
  },
  // ---------------------------------------------------------------- kai
  {
    id: 'kai',
    archetype: 'sword',
    archetypeLabel: 'SWORD / REACH',
    bars: { power: 4, speed: 3, weight: 3, jump: 3, range: 5 },
    weight: 96,
    walkSpeed: 0.11,
    runSpeed: 0.19,
    airSpeed: 0.118,
    airAccel: 0.0085,
    gravity: 0.0088,
    fallSpeed: 0.155,
    fastFallSpeed: 0.25,
    jumpVel: 0.25,
    shortHopVel: 0.17,
    doubleJumpVel: 0.24,
    height: 1.85,
    width: 0.78,
    specials: {
      neutral: { name: 'Tidal Edge', desc: 'Hold to charge a sweeping blade; full charge launches hard.' },
      side: { name: 'Wave Breaker', desc: 'A three-strike sword combo. Press again to continue.' },
      up: { name: 'Riptide Rise', desc: 'A spinning sword ascent that carries foes up with you.' },
      down: { name: 'Undertow Counter', desc: 'Parry a hit and answer with a crushing slash.' },
    },
    finalSmash: { name: 'Riptide Cleave', desc: 'One gigantic tidal slash that sweeps the whole stage.' },
    tip: 'Fight at the tip of your blade. Counter when they swing first!',
    polished: true,
  },
  // ---------------------------------------------------------------- bram
  {
    id: 'bram',
    archetype: 'bruiser',
    archetypeLabel: 'HEAVY BRUISER',
    bars: { power: 5, speed: 1, weight: 5, jump: 2, range: 3 },
    weight: 125,
    walkSpeed: 0.09,
    runSpeed: 0.15,
    airSpeed: 0.1,
    airAccel: 0.007,
    gravity: 0.0095,
    fallSpeed: 0.175,
    fastFallSpeed: 0.27,
    jumpVel: 0.245,
    shortHopVel: 0.165,
    doubleJumpVel: 0.23,
    height: 2.1,
    width: 1.05,
    specials: {
      neutral: { name: 'Boulder Toss', desc: 'Heave a big rock that arcs and bounces once.' },
      side: { name: 'Rockslide Shoulder', desc: 'An armoured shoulder charge — hits do not stop it.' },
      up: { name: 'Mountain Leap', desc: 'A towering leap with a rock-hard rising headbutt.' },
      down: { name: 'Quake Stomp', desc: 'Stomp the ground and send a shockwave both ways.' },
    },
    finalSmash: { name: 'Landslide', desc: 'Split the ground: a quake that buries and launches every foe.' },
    tip: 'Slow but deadly: one charged forward smash ends stocks.',
    polished: true,
  },
  // ---------------------------------------------------------------- rosa
  {
    id: 'rosa',
    archetype: 'bruiser',
    archetypeLabel: 'GRAPPLER',
    bars: { power: 4, speed: 2, weight: 5, jump: 2, range: 2 },
    weight: 118,
    walkSpeed: 0.1,
    runSpeed: 0.175,
    airSpeed: 0.105,
    airAccel: 0.0075,
    gravity: 0.0098,
    fallSpeed: 0.17,
    fastFallSpeed: 0.27,
    jumpVel: 0.25,
    shortHopVel: 0.17,
    doubleJumpVel: 0.235,
    height: 2.0,
    width: 1.0,
    specials: {
      neutral: { name: 'Horn Blast', desc: 'A deafening air-horn shockwave that pushes foes away.' },
      side: { name: 'Big Rig Rush', desc: 'Hold to rev, release to barrel forward with armour.' },
      up: { name: 'Jackknife', desc: 'Spin upward like a wheel, grabbing ledges on the way.' },
      down: { name: 'Tow Hook', desc: 'Command grab that beats shields, then a body-slam.' },
    },
    finalSmash: { name: 'Eighteen Wheeler', desc: 'Summon your rig and run over everyone in your lane.' },
    tip: 'Shield-campers fear Tow Hook. Throw them off the edge!',
    polished: false,
  },
];

export function getFighter(id: string): FighterDef {
  for (let i = 0; i < FIGHTERS.length; i++) if (FIGHTERS[i].id === id) return FIGHTERS[i];
  return FIGHTERS[0];
}

export function fighterIndex(id: string): number {
  for (let i = 0; i < FIGHTERS.length; i++) if (FIGHTERS[i].id === id) return i;
  return 0;
}
