/** Tiny DOM helpers for the party overlays (no framework; DOM is built once and reused). */
export type Attrs = Record<string, string | number | boolean | null | undefined>;

export function h<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  attrs: Attrs | string = {},
  ...children: (Node | string | null | undefined | false)[]
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  if (typeof attrs === 'string') node.className = attrs;
  else
    for (const [k, v] of Object.entries(attrs)) {
      if (v === null || v === undefined || v === false) continue;
      if (k === 'class') node.className = String(v);
      else if (k === 'text') node.textContent = String(v);
      else node.setAttribute(k, v === true ? '' : String(v));
    }
  for (const c of children) {
    if (c === null || c === undefined || c === false) continue;
    node.append(typeof c === 'string' ? document.createTextNode(c) : c);
  }
  return node;
}

export const SVG_NS = 'http://www.w3.org/2000/svg';

/** Parse an SVG markup string into an element (markup is generated by our own code only). */
export function svgFrom(markup: string): SVGSVGElement {
  const tpl = document.createElement('template');
  tpl.innerHTML = markup.trim();
  return tpl.content.firstElementChild as SVGSVGElement;
}

/** Set text only when it changed (avoids layout churn on every render). */
export function setText(node: Element, text: string): void {
  if (node.textContent !== text) node.textContent = text;
}

export function toggle(node: Element, cls: string, on: boolean): void {
  if (node.classList.contains(cls) !== on) node.classList.toggle(cls, on);
}

/** Restart a CSS animation class. */
export function replay(node: HTMLElement | SVGElement, cls: string): void {
  node.classList.remove(cls);
  void (node as HTMLElement).getBoundingClientRect();
  node.classList.add(cls);
}

export function button(label: string, cls: string, onClick: () => void, testId?: string): HTMLButtonElement {
  const b = h('button', { class: `kp-btn ${cls}`.trim(), type: 'button', 'data-testid': testId });
  b.innerHTML = label;
  b.addEventListener('click', (ev) => {
    ev.stopPropagation();
    onClick();
  });
  return b;
}

export function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

export function hex(n: number): string {
  return '#' + ((n >>> 0) & 0xffffff).toString(16).padStart(6, '0');
}

/** Mix a CSS hex colour toward white (t>0) or black (t<0). */
export function shade(hexColor: string, t: number): string {
  const n = parseInt(hexColor.slice(1), 16);
  let r = (n >> 16) & 255,
    g = (n >> 8) & 255,
    b = n & 255;
  const target = t > 0 ? 255 : 0;
  const k = Math.abs(t);
  r = Math.round(r + (target - r) * k);
  g = Math.round(g + (target - g) * k);
  b = Math.round(b + (target - b) * k);
  return '#' + ((r << 16) | (g << 8) | b).toString(16).padStart(6, '0');
}
